import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const url=process.env.TEST_URL||'http://localhost:3017';
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const pages=[],errors=[];const out='.impeccable/review';mkdirSync(out,{recursive:true});
try{
 for(let i=0;i<5;i++){const context=await browser.newContext({viewport:i<2?{width:390,height:844}:{width:1440,height:1000}});let page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));pages.push(page)}
 const host=pages[0];await host.goto(url);await host.getByRole('button',{name:/Host a game/}).click();await host.getByPlaceholder('Name at the table').fill('Browser 0');await host.getByRole('button',{name:'Create room'}).click();await host.getByRole('heading',{name:'Gather the council.'}).waitFor();const code=await host.locator('.room-code>strong').innerText();await host.getByRole('button',{name:/Rang/}).click();await host.waitForTimeout(100);assert.ok(await host.evaluate(()=>document.activeElement.textContent.includes('Rang')),'Theme selection must preserve focus');await host.getByRole('button',{name:'How to play',exact:true}).click();await host.getByText('Character guide',{exact:true}).focus();
 for(let i=1;i<5;i++){let p=pages[i];await p.goto(`${url}/?room=${code}`);await p.getByPlaceholder('Name at the table').fill(`Browser ${i}`);await p.getByRole('button',{name:'Join room'}).click();await p.getByRole('heading',{name:'Gather the council.'}).waitFor()}
 await host.getByRole('heading',{name:'How to play'}).waitFor();for(let i=1;i<5;i++)await host.getByText(`Browser ${i}`).first().waitFor();assert.ok(await host.getByRole('heading',{name:'How to play'}).isVisible(),'Live joins must not close the rules dialog');await host.getByRole('button',{name:'Close rules',exact:true}).click();for(let p of pages)await p.getByRole('button',{name:/Ready up/}).click();await host.getByRole('button',{name:/Deal roles/}).click();
 let seer,blade;
 for(let p of pages){await p.getByRole('button',{name:'Reveal your role',exact:true}).click();const name=await p.locator('.role-caption strong').innerText();if(name==='Merlin')seer=pages.indexOf(p);if(name==='Assassin')blade=p;if(p===host||p===pages[2]){await p.waitForTimeout(650);await p.screenshot({path:`${out}/role-${p===host?'mobile':'desktop'}.png`,fullPage:true})}await p.getByRole('button',{name:/Hide card & confirm role/}).click()}
 for(let round=0;round<3;round++){
  await host.getByText(`Expedition ${round+1}`,{exact:true}).waitFor();let leader;
  for(let p of pages)if(await p.getByRole('heading',{name:'Choose your expedition team.',exact:true}).count())leader=p;
  assert.ok(leader);const teamSize=round===1?3:2;
  for(let i=0;i<teamSize;i++){await leader.getByRole('button',{name:`Select Browser ${i}`,exact:true}).click();assert.equal(await leader.evaluate(()=>document.activeElement.getAttribute('aria-label')),`Deselect Browser ${i}`,'Team selection must preserve focus')}assert.ok(await leader.getByRole('status').first().innerText());
  if(round===0){await host.screenshot({path:`${out}/game-mobile.png`,fullPage:true});await pages[2].screenshot({path:`${out}/game-desktop.png`,fullPage:true});await host.getByRole('button',{name:'My secret card',exact:false}).click();await host.getByRole('dialog',{name:'Your private role'}).waitFor();await host.getByRole('button',{name:'Reveal your role',exact:true}).click();await host.waitForTimeout(650);assert.ok(await host.locator('.role-caption strong').isVisible());await host.screenshot({path:`${out}/private-mobile.png`,fullPage:false});await host.keyboard.press('Escape');assert.equal(await host.getByRole('dialog',{name:'Your private role'}).count(),0);assert.equal(await host.locator('.role-caption').count(),0)}
  await leader.getByRole('button',{name:/Propose team/}).click();for(let p of pages)await p.getByRole('button',{name:'Approve',exact:true}).click();if(round===0)await pages[2].screenshot({path:`${out}/vote-desktop.png`,fullPage:true});await host.getByRole('button',{name:'Begin expedition',exact:true}).click();if(round===0)await host.screenshot({path:`${out}/quest-mobile.png`,fullPage:true});for(let i=0;i<teamSize;i++){await pages[i].getByRole('button',{name:/^Support/}).click();await pages[i].getByRole('button',{name:/Seal my card/}).click()}if(round<2)await host.getByRole('button',{name:'Next expedition',exact:true}).click()
 }
 await blade.getByRole('button',{name:`Select Browser ${seer}`,exact:true}).click();blade.once('dialog',d=>d.accept());await blade.getByRole('button',{name:`Accuse Browser ${seer}`,exact:false}).click();await host.getByRole('heading',{name:'The hidden circle prevails.',exact:true}).waitFor();await host.getByRole('button',{name:'Play again',exact:false}).click();for(let p of [...pages].reverse())await p.getByRole('button',{name:/Leave (room|council)/}).click();assert.deepEqual(errors,[]);console.log('PASS: Five browser players completed create, join, ready, role reveal, team selection, voting, three expeditions, final accusation and rematch. No browser exceptions. Keyboard focus retained on theme/team selection and live room updates; live status populated.');
}finally{await browser.close()}
