import {io} from 'socket.io-client';import assert from 'node:assert/strict';
const url=process.env.TEST_URL||'http://localhost:3017';const clients=[];
async function connect(){let s=io(url,{transports:['websocket'],forceNew:true});let c={s,state:null};s.on('state',x=>c.state=x);await new Promise((res,rej)=>{s.once('connect',res);s.once('connect_error',rej)});clients.push(c);return c}
async function cmd(c,type,data={}){let r=await c.s.timeout(5000).emitWithAck('command',{type,data});assert.ok(r.ok,r.error);await new Promise(r=>setTimeout(r,25));return r}
try{
 let host=await connect();let seat=await cmd(host,'create',{name:'Test host'});for(let i=1;i<5;i++){let c=await connect();c.seat=await cmd(c,'join',{name:'Test '+i,code:seat.code})}for(let c of clients)await cmd(c,'ready');await cmd(host,'start');for(let c of clients){assert.ok(c.state.me.role);assert.ok(c.state.players.every(x=>!x.role&&!x.token));await cmd(c,'ack')}
 const reconnect=clients[4];let originalId=reconnect.state.me.id;reconnect.s.disconnect();await new Promise(r=>setTimeout(r,30));reconnect.s.connect();await new Promise(r=>reconnect.s.once('connect',r));await cmd(reconnect,'resume',{code:seat.code,token:reconnect.seat.token});assert.equal(reconnect.state.me.id,originalId);
 for(let round=0;round<3;round++){let s=host.state,l=clients.find(c=>c.state.me.id===s.leader);let team=s.players.slice(0,s.teamSize).map(p=>p.id);await cmd(l,'propose',{team});await cmd(host,'vote',{approve:true});assert.equal(host.state.history.filter(h=>h.kind==='vote').length,round);for(let c of clients.filter(x=>x!==host))await cmd(c,'vote',{approve:true});assert.equal(host.state.phase,'voteResult');await cmd(l,'continue');for(let c of clients.filter(c=>team.includes(c.state.me.id)))await cmd(c,'quest',{support:true});if(round<2)await cmd(l,'continue')}
 assert.equal(host.state.phase,'accusation');let blade=clients.find(c=>c.state.me.role==='blade'),seer=clients.find(c=>c.state.me.role==='seer');await cmd(blade,'accuse',{id:seer.state.me.id});assert.equal(host.state.winner,'shadow');assert.ok(host.state.players.every(x=>x.role));await cmd(host,'reset');for(let c of [...clients].reverse())await cmd(c,'leave');console.log('PASS: 5 live clients, private roles, reconnect, three expeditions, accusation, rematch and clean room exit.');
}finally{clients.forEach(c=>c.s.disconnect())}
