import test from 'node:test';import assert from 'node:assert/strict';import {room,player,act,view,ROLES,SIZES,EVIL,addPlayer}from'./game.js';
function setup(n=5,options=[]){let p=player('Player 1'),r=room('ABCDEF',p);for(let i=2;i<=n;i++)addPlayer(r,player('Player '+i));r.options=options;r.players.forEach(x=>act(r,x,'ready'));act(r,p,'start');return r}
function begin(r){r.players.forEach(p=>act(r,p,'ack'))}
function expedition(r,sabotage=false){let lead=r.players[r.leader];let evil=r.players.find(x=>ROLES[x.role].side==='shadow');let team=[evil,...r.players.filter(x=>x!==evil)].slice(0,SIZES[r.players.length][r.round]);act(r,lead,'propose',{team:team.map(x=>x.id)});r.players.forEach(x=>act(r,x,'vote',{approve:true}));act(r,lead,'continue');team.forEach(x=>act(r,x,'quest',{support:!(sabotage&&x===evil)}));if(r.phase==='questResult')act(r,lead,'continue')}
test('role counts and team sizes for every supported player count',()=>{for(let n=5;n<=10;n++){let r=setup(n);assert.equal(r.players.filter(x=>ROLES[x.role].side==='shadow').length,EVIL[n]);assert.equal(r.players.filter(x=>x.role==='seer').length,1);assert.equal(r.players.filter(x=>x.role==='blade').length,1);assert.equal(SIZES[n].length,5)}});
test('requires readiness, legal counts, host permission, and capacity',()=>{let r=room('ABCDEF',player('one'));assert.throws(()=>act(r,r.players[0],'start'),/5–10/);for(let i=2;i<=10;i++)addPlayer(r,player('p'+i));assert.throws(()=>addPlayer(r,player('extra')),/10 players/);assert.throws(()=>act(r,r.players[0],'start'),/ready/);assert.throws(()=>act(r,r.players[1],'start'),/host/)});
test('no tokens or other roles in public views; knowledge obeys every special role',()=>{let r=setup(10,['keeper','impostor','veiled','outcast']);for(let p of r.players){let v=view(r,p);assert.ok(v.players.every(x=>!('role'in x)&&!('token'in x)));assert.ok(!JSON.stringify(v).includes(p.token));if(p.role==='seer'){assert.ok(!v.me.knowledge.some(x=>r.players.find(y=>y.id===x.id).role==='veiled'));assert.ok(v.me.knowledge.some(x=>r.players.find(y=>y.id===x.id).role==='outcast'))}if(p.role==='outcast')assert.equal(v.me.knowledge.length,0);if(p.role==='keeper')assert.deepEqual(v.me.knowledge.map(x=>r.players.find(y=>y.id===x.id).role).sort(),['impostor','seer']);if(ROLES[p.role].side==='shadow'&&p.role!=='outcast')assert.ok(v.me.knowledge.every(x=>r.players.find(y=>y.id===x.id).role!=='outcast'))}});
test('three successes reach accusation and wrong accusation gives loyal victory',()=>{let r=setup();begin(r);for(let i=0;i<3;i++)expedition(r);assert.equal(r.phase,'accusation');let blade=r.players.find(x=>x.role==='blade'),target=r.players.find(x=>x.role==='ally');act(r,blade,'accuse',{id:target.id});assert.equal(r.winner,'loyal');assert.ok(view(r,blade).players.every(x=>x.role))});
test('correct final accusation gives conspirators victory',()=>{let r=setup();begin(r);for(let i=0;i<3;i++)expedition(r);act(r,r.players.find(x=>x.role==='blade'),'accuse',{id:r.players.find(x=>x.role==='seer').id});assert.equal(r.winner,'shadow')});
test('three sabotages end the game',()=>{let r=setup();begin(r);for(let i=0;i<3;i++)expedition(r,true);assert.equal(r.phase,'finished');assert.equal(r.winner,'shadow')});
test('ties reject and five consecutive rejections end the game',()=>{let r=setup(6);begin(r);for(let i=0;i<5;i++){let lead=r.players[r.leader];act(r,lead,'propose',{team:r.players.slice(0,2).map(x=>x.id)});r.players.forEach((x,i)=>act(r,x,'vote',{approve:i<3}));if(i<4){assert.equal(r.approved,false);act(r,lead,'continue')}}assert.equal(r.winner,'shadow');assert.equal(r.rejections,5)});
test('loyal sabotage and duplicate or unauthorized actions are rejected',()=>{let r=setup();begin(r);let lead=r.players[r.leader],good=r.players.find(x=>x.role==='seer');assert.throws(()=>act(r,r.players.find(x=>x!==lead),'propose',{team:[]}),/leader/);assert.throws(()=>act(r,lead,'propose',{team:[good.id,good.id]}),/exactly/);act(r,lead,'propose',{team:[good.id,r.players.find(x=>x!==good).id]});act(r,good,'vote',{approve:true});assert.throws(()=>act(r,good,'vote',{approve:true}),/locked/);assert.ok(view(r,good).history.length===0);r.players.filter(x=>x!==good).forEach(x=>act(r,x,'vote',{approve:true}));act(r,lead,'continue');assert.throws(()=>act(r,good,'quest',{support:false}),/must support/);act(r,good,'quest',{support:true});assert.throws(()=>act(r,good,'quest',{support:true}),/locked/);assert.equal(view(r,good).submittedCount,1);assert.ok(!('cards'in view(r,good)))});
test('fourth expedition at seven players requires two sabotages',()=>{let r=setup(7);begin(r);expedition(r,true);expedition(r,false);expedition(r,true);assert.equal(r.round,3);expedition(r,true);assert.equal(r.results[3].success,true);assert.equal(r.results[3].needed,2);assert.equal(r.round,4)});
test('oversubscribed special roles are rejected',()=>assert.throws(()=>setup(5,['impostor','veiled']),/Too many/));
test('approved proposal resets rejections; reset clears roles',()=>{let r=setup();begin(r);r.rejections=4;expedition(r);assert.equal(r.rejections,0);act(r,r.players[0],'reset',{confirm:true});assert.equal(r.phase,'lobby');assert.ok(r.players.every(x=>!x.role&&!x.ready))});
test('host can be reclaimed only after disconnection grace',()=>{let r=setup();let h=r.players[0],p=r.players[1];assert.throws(()=>act(r,p,'claimHost'),/reconnect/);h.online=false;h.offlineAt=Date.now()-61000;act(r,p,'claimHost');assert.equal(r.host,p.id)});
