import { randomInt, randomBytes } from 'node:crypto';
export const SIZES={5:[2,3,2,3,3],6:[2,3,4,3,4],7:[2,3,3,4,4],8:[3,4,4,5,5],9:[3,4,4,5,5],10:[3,4,4,5,5]};
export const EVIL={5:2,6:2,7:3,8:3,9:3,10:4};
export const ROLES={seer:{name:'Merlin',title:'Good',side:'loyal',text:'You know the conspirators. Guide the court without revealing yourself: the Assassin can identify you at the end.'},blade:{name:'Assassin',title:'Evil',side:'shadow',text:'Quietly sabotage expeditions. If the court completes three, identify Merlin to steal victory.'},ally:{name:'Loyal Servant of Arthur',title:'Good',side:'loyal',text:'Find allies through discussion and votes. Complete three expeditions and protect Merlin.'},conspirator:{name:'Minion of Mordred',title:'Evil',side:'shadow',text:'Blend into the court and sabotage expeditions. You may support an expedition to earn trust.'},keeper:{name:'Percival',title:'Good',side:'loyal',text:'You see Merlin and, if present, Morgana. Work out who is who and protect Merlin.'},impostor:{name:'Morgana',title:'Evil',side:'shadow',text:'Percival sees you alongside Merlin. Earn their trust and lead the court astray.'},veiled:{name:'Mordred',title:'Evil',side:'shadow',text:'You are hidden from Merlin. Your fellow conspirators know you.'},outcast:{name:'Oberon',title:'Evil',side:'shadow',text:'You know no conspirators, and they do not know you. Merlin can still see your allegiance.'}};
const fail=m=>{throw new Error(m)};
export const uid=()=>randomBytes(24).toString('hex');
export function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
export function nameOf(value){if(typeof value!=='string')fail('Enter your name.');let n=value.trim().replace(/\s+/g,' ');if(n.length<1||n.length>24)fail('Use a name between 1 and 24 characters.');return n}
export function player(name){return {id:randomBytes(8).toString('hex'),token:uid(),name:nameOf(name),ready:false,online:true,offlineAt:null}}
export function room(code,p,theme='mural'){return {code,host:p.id,theme:['mural','festival','ink'].includes(theme)?theme:'mural',options:[],players:[p],phase:'lobby',createdAt:Date.now(),updatedAt:Date.now(),history:[],round:0,rejections:0}}
export function addPlayer(r,p){if(r.phase!=='lobby')fail('This game has started. Ask the host to start a new game.');if(r.players.length>=10)fail('This room already has 10 players.');if(r.players.some(x=>x.name.toLowerCase()===p.name.toLowerCase()))fail('That name is already taken in this room.');r.players.push(p)}
const leader=r=>r.players[r.leader]?.id;
function finish(r,winner,reason){r.phase='finished';r.winner=winner;r.reason=reason}
function nextLeader(r){r.leader=(r.leader+1)%r.players.length;r.team=[];r.votes={};r.cards={};r.phase='proposal'}
export function act(r,p,type,data={}){
 const host=()=>{if(r.host!==p.id)fail('Only the host can do that.')};
 const phase=s=>{if(r.phase!==s)fail('The game has moved on. Please try the current action.')};
 if(type==='ready'){phase('lobby');p.ready=!p.ready;return}
 if(type==='settings'){host();phase('lobby');if(!['mural','festival','ink'].includes(data.theme))fail('Choose a valid theme.');if(!Array.isArray(data.options)||data.options.some(x=>!['keeper','impostor','veiled','outcast'].includes(x)))fail('Choose valid roles.');r.theme=data.theme;r.options=[...new Set(data.options)];return}
 if(type==='claimHost'){let h=r.players.find(x=>x.id===r.host);if(h?.online||Date.now()-(h?.offlineAt??Date.now())<60000)fail('The host can reconnect. Try again after 60 seconds.');r.host=p.id;return}
 if(type==='remove'){host();phase('lobby');let target=r.players.find(x=>x.id===data.id);if(!target||target.online||target.id===p.id)fail('Only disconnected guests can be removed.');r.players=r.players.filter(x=>x.id!==target.id);return}
 if(type==='reset'){host();if(!['finished','lobby'].includes(r.phase)&&data.confirm!==true)fail('Confirm ending the current game.');r.phase='lobby';r.players.forEach(x=>{x.ready=false;delete x.role});r.history=[];r.round=0;r.rejections=0;delete r.winner;delete r.reason;delete r.accused;r.team=[];r.votes={};r.cards={};return}
 if(type==='start'){
  host();phase('lobby');let n=r.players.length;if(!SIZES[n])fail('Gather 5–10 players to begin.');if(r.players.some(x=>!x.ready||!x.online))fail('Everyone must be online and ready.');
  let evil=['blade',...r.options.filter(x=>ROLES[x].side==='shadow')],good=['seer',...r.options.filter(x=>ROLES[x].side==='loyal')];if(evil.length>EVIL[n])fail('Too many special conspirators for this player count. Turn off a role.');
  while(evil.length<EVIL[n])evil.push('conspirator');while(good.length<n-EVIL[n])good.push('ally');let roles=shuffle([...good,...evil]);r.players.forEach((x,i)=>{x.role=roles[i];x.ack=false});r.phase='reveal';r.leader=randomInt(n);r.round=0;r.rejections=0;r.results=[];r.history=[];r.team=[];r.votes={};r.cards={};return;
 }
 if(type==='ack'){phase('reveal');p.ack=true;if(r.players.every(x=>x.ack))r.phase='proposal';return}
 if(type==='propose'){phase('proposal');if(leader(r)!==p.id)fail('Only the expedition leader chooses a team.');if(!Array.isArray(data.team)||data.team.length!==SIZES[r.players.length][r.round]||new Set(data.team).size!==data.team.length||data.team.some(id=>!r.players.some(x=>x.id===id)))fail('Choose exactly the required number of players.');r.team=data.team;r.votes={};r.phase='vote';return}
 if(type==='vote'){phase('vote');if(typeof data.approve!=='boolean')fail('Choose Approve or Reject.');if(p.id in r.votes)fail('Your vote is already locked.');r.votes[p.id]=data.approve;if(Object.keys(r.votes).length===r.players.length){r.approved=Object.values(r.votes).filter(Boolean).length>r.players.length/2;r.history.push({kind:'vote',round:r.round+1,leader:leader(r),team:[...r.team],votes:{...r.votes},approved:r.approved});if(!r.approved)r.rejections++;else r.rejections=0;if(r.rejections===5)finish(r,'shadow','Five consecutive teams were rejected.');else r.phase='voteResult'}return}
 if(type==='continue'){if(p.id!==leader(r)&&p.id!==r.host)fail('The leader or host will continue.');if(r.phase==='voteResult'){if(r.approved){r.cards={};r.phase='quest'}else nextLeader(r);return}if(r.phase==='questResult'){r.round++;nextLeader(r);return}fail('There is no result to continue yet.')}
 if(type==='quest'){phase('quest');if(!r.team.includes(p.id))fail('Only this expedition’s members submit cards.');if(p.id in r.cards)fail('Your card is already locked.');if(typeof data.support!=='boolean')fail('Choose a card.');if(!data.support&&ROLES[p.role].side==='loyal')fail('Loyal players must support the expedition.');r.cards[p.id]=data.support;if(Object.keys(r.cards).length===r.team.length){let sabotages=Object.values(r.cards).filter(x=>!x).length;let needed=r.players.length>=7&&r.round===3?2:1;let success=sabotages<needed;r.results.push({success,sabotages,needed,team:[...r.team]});r.history.push({kind:'quest',round:r.round+1,success,sabotages,needed,team:[...r.team]});r.cards={};if(r.results.filter(x=>!x.success).length===3)finish(r,'shadow','Three expeditions were sabotaged.');else if(r.results.filter(x=>x.success).length===3)r.phase='accusation';else r.phase='questResult'}return}
 if(type==='accuse'){phase('accusation');if(p.role!=='blade')fail('Only the Assassin makes the final accusation.');let target=r.players.find(x=>x.id===data.id);if(!target||ROLES[target.role].side!=='loyal')fail('Choose a member of the loyal court.');r.accused=target.id;finish(r,target.role==='seer'?'shadow':'loyal',target.role==='seer'?'The Assassin identified Merlin.':'Three expeditions succeeded, and Merlin survived.');return}
 fail('Unknown action.');
}
export function view(r,p){
 const active=r.phase!=='lobby',over=r.phase==='finished';let knowledge=[];
 if(active&&p.role){if(p.role==='seer')knowledge=r.players.filter(x=>ROLES[x.role].side==='shadow'&&x.role!=='veiled').map(x=>({id:x.id,label:'Evil'}));else if(p.role==='keeper')knowledge=r.players.filter(x=>['seer','impostor'].includes(x.role)).map(x=>({id:x.id,label:'Merlin or Morgana'}));else if(ROLES[p.role].side==='shadow'&&p.role!=='outcast')knowledge=r.players.filter(x=>ROLES[x.role].side==='shadow'&&x.role!=='outcast'&&x.id!==p.id).map(x=>({id:x.id,label:'Fellow evil player'}))}
 return {code:r.code,host:r.host,theme:r.theme,options:r.options,phase:r.phase,players:r.players.map(x=>({id:x.id,name:x.name,ready:x.ready,online:x.online,offlineAt:x.offlineAt,ack:!!x.ack,...(over?{role:x.role}:{})})),me:{id:p.id,...(active?{role:p.role,knowledge}:{}),voted:!!r.votes&&p.id in r.votes,submitted:!!r.cards&&p.id in r.cards},leader:leader(r),round:r.round,team:r.team??[],teamSize:SIZES[r.players.length]?.[r.round],rejections:r.rejections,results:r.results??[],history:r.history,submittedCount:Object.keys(r.cards??{}).length,votedIds:Object.keys(r.votes??{}),approved:r.approved,winner:r.winner,reason:r.reason,accused:r.accused,accusationTargets:r.phase==='accusation'&&p.role==='blade'?r.players.filter(x=>ROLES[x.role].side==='loyal').map(x=>x.id):[]};
}
