import React,{useState,useEffect,useRef,createContext,useContext} from 'react';
import {createRoot} from 'react-dom/client';
import {io} from 'socket.io-client';
import {ArrowRight,ArrowLeft,Users,Clock,BookOpen,Check,Copy,Eye,EyeOff,Shield,Sun,MoveUpRight,X,Link as LinkIcon,WifiOff,Crown,Scroll,CheckCircle,Circle,LogOut,Sparkles,ChevronRight,Plus,LockKeyhole,Flower2,ScanEye,Layers,Map,Flag,Volume2,VolumeX} from 'lucide-react'
import {MorphIcon} from 'morphicons/react';
import {Volume2 as VolumeOnData,VolumeX as VolumeOffData,Check as CheckData,X as XData,ChevronRight as ChevronRightData,ChevronDown as ChevronDownData,Eye as EyeData,EyeOff as EyeOffData} from 'lucide';;
import {ROLES,SIZES,EVIL} from '../server/game-client.js';
import './style.css';
import {GameIcon} from './GameIcon.jsx';
import {playSound,soundEnabled,setSoundEnabled} from './sound.js';
import './tabletop.css';
import './chamber.css';
import './council-ui.css';
import {themes,roleOrder} from './themes.js';
const socket=io({autoConnect:false});
function savedSeat(){try{return JSON.parse(sessionStorage.getItem('sabha-seat')||'null')}catch{sessionStorage.removeItem('sabha-seat');return null}}
const UIContext=createContext(null);
function tableSound(e){const button=e.target.closest('button,summary');if(!button||button.disabled||button.dataset.silent)return;playSound(button.classList.contains('secret-card')?'reveal':button.classList.contains('world-panel')||button.closest('.world-tabs')?'select':'tap',true)}
function reflectCard(e){if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const card=e.target.closest('.foil-surface');if(!card)return;const r=card.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));card.style.setProperty('--light-x',`${x*100}%`);card.style.setProperty('--light-y',`${y*100}%`);card.style.setProperty('--tilt-x',`${(0.5-y)*5}deg`);card.style.setProperty('--tilt-y',`${(x-0.5)*6}deg`);card.dataset.lit='true'}
function resetReflection(e){const card=e.target.closest('.foil-surface');if(!card||card.contains(e.relatedTarget))return;delete card.dataset.lit;card.style.removeProperty('--tilt-x');card.style.removeProperty('--tilt-y')}
function touchReflection(e){if(e.pointerType!=='touch')return;const card=e.target.closest('.foil-surface');if(!card)return;card.classList.remove('touch-shine');void card.offsetWidth;card.classList.add('touch-shine')}

function App(){
 const helpRef=useRef(null),drawerRef=useRef(null),lastPhase=useRef(null);
 const [sound,setSound]=useState(soundEnabled);
 const [roleRead,setRoleRead]=useState(false);
 const revealRole=value=>{setShown(value);if(value)setRoleRead(true)};

 const [state,setState]=useState(null),[connected,setConnected]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(false),[screen,setScreen]=useState(new URLSearchParams(location.search).get('room')?'join':'home'),[name,setName]=useState(localStorage.getItem('sabha-name')||''),[code,setCode]=useState(new URLSearchParams(location.search).get('room')||''),[theme,setTheme]=useState('mural'),[help,setHelp]=useState(false),[shown,setShown]=useState(false),[team,setTeam]=useState([]),[target,setTarget]=useState(''),[copied,setCopied]=useState(false),[notice,setNotice]=useState(''),[privateOpen,setPrivateOpen]=useState(false),[previewBack,setPreviewBack]=useState(false);
 useEffect(()=>{const key=state?`${state.code}:${state.phase}:${state.round}`:null;if(lastPhase.current&&key&&key!==lastPhase.current)playSound('phase');lastPhase.current=key},[state?.code,state?.phase,state?.round]);
 useEffect(()=>{
  socket.on('connect',()=>{setConnected(true);const s=savedSeat();if(s)socket.emit('command',{type:'resume',data:s},r=>{if(!r.ok){sessionStorage.removeItem('sabha-seat');setError(r.error);setState(null)}})});
  socket.on('disconnect',()=>{setConnected(false);setShown(false)});socket.on('connect_error',()=>setConnected(false));
  socket.on('state',s=>{setState(s);setError('')});socket.on('removed',()=>{sessionStorage.removeItem('sabha-seat');setState(null);setError('Your seat was removed or this room expired. You can join a new room.');setScreen('join')});socket.connect();return()=>{socket.removeAllListeners();socket.disconnect()}
 },[]);
 useEffect(()=>{setShown(false);setRoleRead(false);setPrivateOpen(false);setTeam([]);setTarget('')},[state?.phase,state?.round]);
 useEffect(()=>{if(!help)return;const previous=document.activeElement;helpRef.current.querySelector('button')?.focus();const esc=e=>{if(e.key==='Escape')setHelp(false);if(e.key==='Tab'){const a=[...helpRef.current.querySelectorAll('button,summary,a[href],input')].filter(x=>x.getClientRects().length);const first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',esc);return()=>{document.removeEventListener('keydown',esc);requestAnimationFrame(()=>previous?.isConnected&&previous.focus())}},[help]);
 useEffect(()=>{const hide=()=>{if(document.hidden){setShown(false);setPrivateOpen(false)}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[]);
 useEffect(()=>{if(!privateOpen)return;const previous=document.activeElement;const drawer=drawerRef.current;drawer.querySelector('button')?.focus();const handle=e=>{if(e.key==='Escape'){setPrivateOpen(false);setShown(false)}if(e.key==='Tab'){const nodes=[...drawer.querySelectorAll('button')].filter(x=>x.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus()}}};drawer.addEventListener('keydown',handle);const resize=()=>{if(innerWidth>760){setPrivateOpen(false);setShown(false)}};window.addEventListener('resize',resize);return()=>{drawer.removeEventListener('keydown',handle);window.removeEventListener('resize',resize);requestAnimationFrame(()=>previous?.isConnected&&previous.focus())}},[privateOpen]);
 useEffect(()=>{
  const frame=requestAnimationFrame(()=>document.querySelector('main h1')?.focus());
  return()=>cancelAnimationFrame(frame);
 },[screen,state?.phase]);
 useEffect(()=>{
  const modal=help?helpRef.current:privateOpen?drawerRef.current:null;
  if(!modal)return;
  const changed=[];let node=modal;
  while(node&&node!==document.body){for(const sibling of node.parentElement?.children||[]){if(sibling!==node&&!sibling.classList.contains('private-scrim')&&!sibling.inert){sibling.inert=true;changed.push(sibling)}}node=node.parentElement}
  const overflow=document.body.style.overflow;document.body.style.overflow='hidden';
  return()=>{changed.forEach(node=>node.inert=false);document.body.style.overflow=overflow};
 },[help,privateOpen]);
 async function command(type,data={}){if(pending)return;if(!connected){setError('Connection lost. We’ll reconnect automatically; your seat is saved.');return}setPending(true);setError('');return new Promise(resolve=>socket.timeout(8000).emit('command',{type,data},(err,r)=>{setPending(false);if(err){setError('The server did not respond. Reconnect before trying again.');resolve(false);return}if(!r.ok){setError(r.error);resolve(false);return}if(r.token){sessionStorage.setItem('sabha-seat',JSON.stringify({code:r.code,token:r.token}));localStorage.setItem('sabha-name',name);history.replaceState(null,'',`?room=${r.code}`)}if(type==='leave'){sessionStorage.removeItem('sabha-seat');setState(null);setScreen('home');history.replaceState(null,'','/')}resolve(true)}))}
 const currentTheme=themes.find(t=>t.id===(state?.theme||theme));
 const me=state?.players.find(x=>x.id===state.me.id),isHost=state?.host===state?.me.id,isLeader=state?.leader===state?.me.id;
 const pname=id=>state?.players.find(p=>p.id===id)?.name||'Player';
 const copy=async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?room=${state.code}`);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setNotice(`Invite friends: ${location.origin}/?room=${state.code}`)}};
 return <UIContext.Provider value={{state,currentTheme,pending,command,setTheme,setScreen,setError,shown,setShown:revealRole,pname,team,setTeam,target,setTarget,me,isHost,isLeader,helpRef,setHelp,privateOpen,setPrivateOpen,previewBack,setPreviewBack}}><div className={`app theme-${currentTheme.id} ${!state&&screen==='home'?'is-home':'in-council'}`} onClickCapture={tableSound} onPointerMove={reflectCard} onPointerOver={reflectCard} onPointerOut={resetReflection} onPointerDown={touchReflection}><div className="chamber-backdrop" aria-hidden="true"/><a className="skip-link" href="#game-content">Skip to game</a><header className="site-header"><a className="wordmark" href="/" onClick={e=>{e.preventDefault();if(!state)setScreen('home')}}><span className="brand-mark"><GameIcon kind="eye" size={30}/></span><span>GUPT SABHA<small>THE SECRET COUNCIL</small></span></a><nav><button className="sound-toggle" data-silent="true" aria-label={sound?'Mute sound effects':'Enable sound effects'} aria-pressed={sound} onClick={()=>{setSoundEnabled(!sound);setSound(!sound)}}><MorphIcon icon={sound?VolumeOnData:VolumeOffData} size={18} spring="snappy" reducedMotion="user"/><span className="sound-label"><span data-active={sound}>Sound on</span><span data-active={!sound}>Sound off</span></span></button><button className="text-button" aria-label="How to play" onClick={()=>{setShown(false);setHelp(true)}}><GameIcon kind="scroll" size={22}/> How to play</button>{state?<span className="connection"><i className={connected?'online':''}/>{connected?'Connected':'Reconnecting'}</span>:<span className="header-note">5–10 friends. Two hidden sides.</span>}</nav></header>
 <main id="game-content" tabIndex={-1}><div className="sr-only" role="status" aria-live="polite" aria-atomic="true">{state?`${({lobby:"Waiting in the lobby",reveal:"Read your private role",proposal:isLeader?"Your turn: choose an expedition team":"The leader is choosing a team",vote:state.me.voted?"Your vote is sealed":"Vote to approve or reject the team",voteResult:state.approved?"Team approved":"Team rejected",quest:state.team.includes(state.me.id)?"Submit your expedition card":"Waiting for the expedition",questResult:state.results.at(-1)?.success?"Expedition succeeded":"Expedition failed",accusation:"The Assassin will make the final accusation",finished:state.winner==="loyal"?"The loyal court wins":"The hidden circle wins"})[state.phase]}.${state.phase==="vote"?` ${state.votedIds.length} of ${state.players.length} votes sealed.`:""}`:""}</div>{!connected&&<div className="connection-banner" role="status"><WifiOff size={16}/> Connecting to the council… Your seat and progress are saved.</div>}{error&&<div className="error-banner" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="notice" role="status">{notice}</div>}
 {!state&&screen==='home'&&<Home/>}
 {!state&&screen!=='home'&&<section className="entry-layout"><div className="entry-copy"><Back/><h1 tabIndex={-1}>{screen==='create'?'Host a game.':'Join your friends.'}</h1><p>{screen==='create'?'Create a private room, then share the invite. You’ll choose roles together before the game begins.':'Enter the room code your host shared. A name is all you need.'}</p><div className="entry-art foil-surface"><ThemeArt index={themes.findIndex(t=>t.id===theme)}/></div></div><form className="entry-form" onSubmit={e=>{e.preventDefault();command(screen==='create'?'create':'join',screen==='create'?{name,theme}:{name,code})}}><h2>{screen==='create'?'Create your room':'Join the council'}</h2><label>Your name<input value={name} autoFocus onChange={e=>setName(e.target.value)} maxLength={24} autoComplete="nickname" placeholder="Name at the table" required/></label>{screen==='join'?<label>Room code<input className="code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6))} minLength={6} maxLength={6} placeholder="ABCDEF" autoCapitalize="characters" autoComplete="off" required/></label>:<><p className="field-title">Choose your deck</p><ThemePicker compact/></>}<button className="primary wide" disabled={pending||!connected}>{pending?'Connecting…':screen==='create'?'Create room':'Join room'}<ArrowRight size={18}/></button><p className="form-note">{screen==='create'?'You’ll get a private link and room code to share.':'Your role stays private on your device.'}</p></form></section>}
 {state&&state.phase==='lobby'&&<><section className="room-heading"><div><h1 tabIndex={-1}>Gather the council.</h1><p>Share the room code. When everyone is here, ready up to receive your roles.</p></div><div className="room-code"><span>ROOM CODE</span><strong>{state.code}</strong><button className="text-button" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Link copied':'Copy invite link'}</button></div></section><div className="lobby-grid"><section><div className="section-label"><h2>At the table <span className="count">{state.players.length}/10</span></h2><span>{state.players.length<5?`${5-state.players.length} more to start`:`${state.players.filter(p=>p.ready).length} ready`}</span></div><CouncilSeats/><div className="lobby-actions"><button className={me.ready?'secondary':'primary'} disabled={pending} onClick={()=>command('ready')}><MorphIcon icon={me.ready?XData:CheckData} size={18} spring="snappy" reducedMotion="user"/>{me.ready?' Ready · cancel':' Ready up'}</button>{isHost&&<button className="primary" disabled={pending||state.players.length<5||1+state.options.filter(k=>ROLES[k].side==='shadow').length>EVIL[state.players.length]||state.players.some(p=>!p.ready||!p.online)} onClick={()=>command('start')}>Deal roles <ArrowRight size={18}/></button>}</div><LobbyStatus/><button className="text-button" onClick={()=>command('leave')}><LogOut size={15}/> Leave room</button></section><aside className="lobby-settings"><h2>Your deck</h2><ThemePicker compact disabled={!isHost}/><PowerCards/><div className="host-tip"><BookOpen size={21}/><p><strong>A first-timer at your table?</strong><br/>Keep the standard roles. We’ll explain every step as you go.</p></div></aside></div></>}
 {state&&state.phase!=='lobby'&&<><section className="game-heading"><div><span className="room-inline">Council {state.code}</span><h1 tabIndex={-1}>{state.phase==='finished'?'The truth comes to light.':state.phase==='reveal'?'Discover your role.':state.phase==='accusation'?'One final accusation.':`Expedition ${state.round+1}`}</h1></div><div className="expedition-track" aria-label="Expedition results">{[0,1,2,3,4].map(i=><div key={i} role="img" aria-label={`Expedition ${i+1}: ${state.results[i]?(state.results[i].success?"succeeded":"failed"):i===state.round?"current":"upcoming"}; ${SIZES[state.players.length][i]} players${state.players.length>=7&&i===3?"; two sabotages required":""}`} className={`${state.results[i]?(state.results[i].success?'success':'failure'):i===state.round?'current':''}`}><span>{state.results[i]?(state.results[i].success?<Check size={20}/>:<X size={20}/>):i+1}</span><small>{SIZES[state.players.length][i]} players{state.players.length>=7&&i===3?' *':''}</small></div>)}</div></section><Scoreboard/><PhaseGuide/><div className={`game-grid phase-${state.phase}`}><section className="play-area">
 {state.phase==='reveal'&&<><h2>Read your role. Keep it secret.</h2><p>Reveal your card privately. Read your allegiance and what you know, then confirm below to begin.</p><p className="progress-text">{state.players.filter(x=>x.ack).length} of {state.players.length} players have read their roles.</p><button className="primary" disabled={pending||me.ack||!roleRead} onClick={()=>{setShown(false);command('ack')}}>{me.ack?'Role confirmed':!roleRead?'Reveal your card first':'Hide card & confirm role'}<Check size={18}/></button></>}
 {state.phase==='proposal'&&<><h2>{isLeader?'Choose your expedition team.':`${pname(state.leader)} is choosing a team.`}</h2><p>{isLeader?`Choose ${state.teamSize} people for this expedition. You may include yourself.`:'Discuss who should go. Watch the proposals; they can tell you a lot.'}</p>{state.players.length>=7&&state.round===3&&<p className="rule-note">This expedition needs two sabotage cards to fail.</p>}<PlayerList selectable={isLeader}/>{isLeader&&<p className="decision-hint" role="status">{team.length===state.teamSize?"Team complete. Deselect a player to change your team.":`${state.teamSize-team.length} more to choose.`}</p>}{isLeader&&<button className="primary wide" disabled={pending||team.length!==state.teamSize} onClick={()=>command('propose',{team})}>Propose team · {team.length}/{state.teamSize}<ArrowRight size={18}/></button>}</>}
 {state.phase==='vote'&&<><h2>Approve this team?</h2><p>Proposed by {pname(state.leader)}. Everyone votes. More than half must approve.</p><div className="team-names">{state.team.map(id=><span key={id}>{pname(id)}</span>)}</div>{state.me.voted?<div className="waiting"><CheckCircle/><strong>Your vote is sealed.</strong><span>Waiting for the rest of the council.</span></div>:<div className="vote-actions"><button className="primary" disabled={pending} onClick={()=>command('vote',{approve:true})}><Check/> Approve</button><button className="secondary" disabled={pending} onClick={()=>command('vote',{approve:false})}><X/> Reject</button></div>}<p className="progress-text">{state.votedIds.length} of {state.players.length} votes sealed</p><PlayerList/></>}
 {state.phase==='voteResult'&&<><h2>{state.approved?'Team approved.':'Team rejected.'}</h2><p>{state.approved?'This team will now play their expedition cards in secret.':'Leadership passes to the next player for a new proposal.'}</p><div className="vote-results">{state.players.map(p=><div key={p.id}><span>{p.name}</span><strong className={state.history.at(-1).votes[p.id]?'good-text':'bad-text'}>{state.history.at(-1).votes[p.id]?'Approve':'Reject'}</strong></div>)}</div>{(isLeader||isHost)?<button className="primary" disabled={pending} onClick={()=>command('continue')}>{state.approved?'Begin expedition':'Next proposal'}<ArrowRight size={17}/></button>:<p className="muted">The leader or host will continue.</p>}</>}
 {state.phase==='quest'&&<><h2>{state.team.includes(me.id)?'Choose your expedition card.':'The expedition is underway.'}</h2><p>Only team members submit a card. The result reveals how many sabotages were played, never who played them.</p><div className="team-names">{state.team.map(id=><span key={id}>{pname(id)}</span>)}</div>{state.team.includes(me.id)&&!state.me.submitted?<QuestDecision/>:<div className="waiting"><GameIcon kind="sword" size={44}/><strong>{state.me.submitted?'Your card is sealed.':'Waiting for the expedition.'}</strong></div>}<p className="progress-text">{state.submittedCount} of {state.team.length} cards submitted</p></>}
 {state.phase==='questResult'&&<><div className={`result-emblem ${state.results.at(-1).success?'good-text':'bad-text'}`}>{state.results.at(-1).success?<Sun size={56}/>:<X size={56}/>}</div><h2>{state.results.at(-1).success?'The expedition succeeds.':'Expedition failed.'}</h2><p>{state.results.at(-1).sabotages} sabotage {state.results.at(-1).sabotages===1?'card':'cards'} revealed. {state.results.at(-1).needed} needed to fail.</p>{(isLeader||isHost)?<button className="primary" disabled={pending} onClick={()=>command('continue')}>Next expedition<ArrowRight size={17}/></button>:<p className="muted">The leader or host will continue.</p>}</>}
 {state.phase==='accusation'&&<><h2>Three successes. One last secret.</h2><p>The Assassin has one chance to identify Merlin. The hidden circle may discuss before the Assassin decides.</p>{state.me.role==='blade'?<><PlayerList selectable targets={state.accusationTargets}/><button className="primary wide" disabled={!target||pending} onClick={()=>{if(confirm(`Accuse ${pname(target)} of being Merlin? This ends the game.`))command('accuse',{id:target})}}>Accuse {target?pname(target):'Merlin'}<ArrowRight size={17}/></button></>:<div className="waiting"><Eye/><strong>The Assassin is deciding.</strong><span>Protect Merlin’s identity until the end.</span></div>}</>}
 {state.phase==='finished'&&<><div className="result-emblem"><GameIcon kind="crown" size={60}/></div><h2>{state.winner==='loyal'?'The loyal court prevails.':'The hidden circle prevails.'}</h2><p>{state.reason}</p>{state.accused&&<p>The Assassin accused <strong>{pname(state.accused)}</strong>.</p>}<div className="role-results">{state.players.map(p=><div key={p.id}><strong>{p.name}</strong><span className={ROLES[p.role].side==='loyal'?'good-text':'bad-text'}>{ROLES[p.role].name} · {ROLES[p.role].title}</span></div>)}</div><div className="lobby-actions">{isHost&&<button className="primary" disabled={pending} onClick={()=>command('reset')}>Play again<ArrowRight size={17}/></button>}<button className="secondary" onClick={()=>command('leave')}>Leave council</button></div></>}
 {state.phase!=='reveal'&&state.phase!=='finished'&&<div className="rejection-track"><span>Rejected teams</span><span aria-label={`${state.rejections} of 5 teams rejected`}>{[0,1,2,3,4].map(i=><i key={i} className={i<state.rejections?'filled':''}/>)}</span><small>5 in a row → hidden circle wins</small></div>}
 </section><aside>{state.phase!=='finished'&&<div ref={drawerRef} role={privateOpen?"dialog":undefined} aria-modal={privateOpen||undefined} aria-label={privateOpen?"Your private role":undefined} className={`private-drawer ${privateOpen?'is-open':''}`}><button className="drawer-close text-button" onClick={()=>{setPrivateOpen(false);setShown(false)}}><X size={18}/> Close private card</button><RoleCard/></div>}<details className="history" open={state.phase==='finished'}><summary><Scroll size={17}/> Council record <span>{state.history.length}</span></summary>{state.history.length===0?<p className="muted small">Team votes and expedition results appear here as you play.</p>:state.history.map((h,i)=><div className="history-entry" key={i}><strong>Expedition {h.round} · {h.kind==='vote'?(h.approved?'Team approved':'Team rejected'):(h.success?'Succeeded':'Failed')}</strong><p>{h.kind==='vote'?`${pname(h.leader)} proposed ${h.team.map(pname).join(', ')}. ${Object.values(h.votes).filter(Boolean).length}/${state.players.length} approved.`:`${h.sabotages} sabotage cards. ${h.needed} needed to fail.`}</p>{h.kind==='vote'&&<small>{Object.entries(h.votes).map(([id,v])=>`${pname(id)}: ${v?'yes':'no'}`).join(' · ')}</small>}</div>)}</details>{isHost&&state.phase!=='finished'&&<button className="text-button end-game" onClick={()=>{if(confirm('End this game and return everyone to the lobby? Current game progress will be cleared.'))command('reset',{confirm:true})}}>End game & return to lobby</button>}</aside></div></>}
 {state&&!state.players.find(p=>p.id===state.host)?.online&&!isHost&&<div className="host-recovery"><p>The host disconnected. Their seat is saved. After 60 seconds, you may take over hosting.</p><button className="secondary" onClick={()=>command('claimHost')}>Become host</button></div>}
 {privateOpen&&<div className="private-scrim" aria-hidden="true" onClick={()=>{setPrivateOpen(false);setShown(false)}}/>}
 {state&&!['lobby','finished','reveal'].includes(state.phase)&&<button className="private-shortcut" onClick={()=>{setPrivateOpen(!privateOpen);setShown(false)}} aria-expanded={privateOpen}><LockKeyhole size={18}/><span>{privateOpen?'Close my card':'My secret card'}</span><MorphIcon icon={privateOpen?EyeOffData:EyeData} size={18} spring="snappy" reducedMotion="user"/></button>}
 </main><footer><span><ScanEye size={18}/> GUPT SABHA</span><span>A little mystery brings everyone together.</span><button className="text-button" onClick={()=>setHelp(true)}>The rules <ArrowRight size={14}/></button></footer>{help&&<Rules/>}</div></UIContext.Provider>
}
 function ThemeArt({index=0,role=0,className=''}){const t=themes[index];return <div className={`theme-art atlas-art ${className}`} style={{backgroundImage:`url(${t.file})`,backgroundPosition:`${role%3*50}% ${Math.floor(role/3)*50}%`}} role="img" aria-label={`${t.name} ${role===8?'card back':ROLES[roleOrder[role]]?.name+' illustration'}`}/>}

 function ThemePicker({compact=false,disabled=false}){const {state,currentTheme,pending,command,setTheme,setScreen,setError,shown,setShown,pname,team,setTeam,target,setTarget,me,isHost,helpRef,setHelp}=useContext(UIContext);return <div className={`theme-picker ${compact?'compact':''}`} role="group" aria-label="Art theme">{themes.map((t,i)=><button type="button" key={t.id} className={`theme-option ${currentTheme.id===t.id?'selected':''}`} disabled={disabled||pending} aria-pressed={currentTheme.id===t.id} onClick={()=>state?command('settings',{theme:t.id,options:state.options}):setTheme(t.id)}><ThemeArt index={i}/><span><strong>{t.name}</strong><small>{t.style}</small></span><span className="radio">{currentTheme.id===t.id&&<Check size={13}/>}</span></button>)}</div>}
 function Back(){const {state,currentTheme,pending,command,setTheme,setScreen,setError,shown,setShown,pname,team,setTeam,target,setTarget,me,isHost,helpRef,setHelp}=useContext(UIContext);return <button className="text-button" onClick={()=>{setScreen('home');setError('')}}><ArrowLeft size={16}/> Back to menu</button>}
 function RoleCard(){const {state,currentTheme,shown,setShown,pname}=useContext(UIContext);const role=ROLES[state.me.role],idx=themes.indexOf(currentTheme);return <section className="private-panel"><div className="section-label"><h2>Your secret</h2><span><LockKeyhole size={13}/> PRIVATE</span></div><button className={`secret-card foil-surface ${shown?'revealed':''}`} onClick={()=>setShown(!shown)} aria-label={shown?'Hide your role':'Reveal your role'}><div className="card-turn" aria-hidden="true"><div className="card-face card-back"><ThemeArt index={idx} role={8}/><span className="back-caption"><GameIcon kind="eye" size={25}/><strong>GUPT SABHA</strong><small>Tap to reveal your role</small></span></div><div className="card-face card-front">{shown&&<><ThemeArt index={idx} role={roleOrder.indexOf(state.me.role)}/><span className="role-caption"><small>{role.side==='loyal'?<Sun size={12}/>:<Eye size={12}/>} {role.side==='loyal'?'LOYAL COURT':'HIDDEN CIRCLE'}</small><strong>{role.name}</strong><span>{role.title}</span></span></>}</div></div></button>{shown?<div className="role-instructions"><h3>{role.name} · {role.side==='loyal'?'Loyal court':'Hidden circle'}</h3><p>{role.text}</p>{state.me.knowledge.length>0&&<><strong>What you know</strong><ul>{state.me.knowledge.map(k=><li key={k.id}>{pname(k.id)} <span>— {k.label}</span></li>)}</ul></>}<button className="text-button" onClick={()=>setShown(false)}><EyeOff size={15}/> Hide my role</button></div>:<p className="muted small">Reveal only when your screen is private. Select the card again to hide it.</p>}</section>}

 function PlayerList({selectable=false,targets=null}){const {state,currentTheme,pending,command,setTheme,setScreen,setError,shown,setShown,pname,team,setTeam,target,setTarget,me,isHost,helpRef,setHelp}=useContext(UIContext);return <div className="player-list">{state.players.map((p,i)=>{const selected=targets?target===p.id:team.includes(p.id);const allowed=selectable&&(!targets||targets.includes(p.id));return <div key={p.id} className={`player-row ${selected?'chosen':''} ${p.id===state.leader?'leader-row':''}`}><span className="avatar">{p.name.charAt(0).toUpperCase()}</span><span className="player-name"><strong>{p.name}{p.id===me.id&&<small> (you)</small>}</strong><small>{p.id===state.host?'Host':`Seat ${i+1}`}{p.id===state.leader&&state.phase!=='lobby'?' · Expedition leader':''}{!p.online?' · Reconnecting':''}</small></span>{state.phase==='lobby'?<>{p.ready?<span className="status ready"><Check size={13}/>Ready</span>:<span className="status">Joining</span>}{isHost&&!p.online&&p.id!==me.id&&<button className="icon-button" aria-label={`Remove ${p.name}`} onClick={()=>command('remove',{id:p.id})}><X size={16}/></button>}</>:allowed?<button className={`select-player ${selected?'selected':''}`} disabled={pending||(!targets&&!selected&&team.length>=state.teamSize)} aria-label={`${selected?'Deselect':'Select'} ${p.name}`} aria-pressed={selected} onClick={()=>targets?setTarget(p.id):setTeam(a=>a.includes(p.id)?a.filter(x=>x!==p.id):a.length<state.teamSize?[...a,p.id]:a)}>{selected?<Check size={18}/>:<Plus size={17}/>}<span>{selected?'Selected':'Select'}</span></button>:<>{state.team.includes(p.id)&&<span className="status">On team</span>}{state.phase==='vote'&&state.votedIds.includes(p.id)&&<Check size={17}/>}</>}</div>})}</div>}
 function Rules(){const {state,currentTheme,pending,command,setTheme,setScreen,setError,shown,setShown,pname,team,setTeam,target,setTarget,me,isHost,helpRef,setHelp}=useContext(UIContext);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setHelp(false)}}><section ref={helpRef} className="rules-modal" role="dialog" aria-modal="true" aria-labelledby="rules-title"><button className="icon-button close" onClick={()=>setHelp(false)} aria-label="Close rules"><X/></button><h2 id="rules-title">How to play</h2><p>Two secret sides share one council. Talk together in person or on your favourite voice call.</p><ol className="rules-steps"><li><strong>Discover your role.</strong><p>The loyal court wants three successful expeditions. The hidden circle wants three failures.</p></li><li><strong>Choose who to trust.</strong><p>The leader proposes a team. Everyone votes; more than half must approve. A tie rejects. Leadership rotates.</p></li><li><strong>Play your card in secret.</strong><p>Team members choose Support or Sabotage. Loyal players must support. One sabotage usually fails an expedition; expedition four needs two at 7–10 players.</p></li><li><strong>Protect Merlin.</strong><p>After three successes, the Assassin gets one chance to identify Merlin. A correct accusation gives the hidden circle victory.</p></li></ol><p className="rule-note">Five rejected teams in a row also give the hidden circle victory. No one is eliminated, so everyone stays in the conversation.</p><details open><summary>Character guide</summary><div className="role-guide">{['loyal','shadow'].map(side=><React.Fragment key={side}><h3 className={`role-side ${side==='loyal'?'good-text':'bad-text'}`}>{side==='loyal'?'Loyal court · Good':'Hidden circle · Evil'}</h3>{Object.entries(ROLES).filter(([,r])=>r.side===side).map(([id,r])=><figure key={id} className={`role-entry ${r.side}`}><ThemeArt index={Math.max(0,themes.indexOf(currentTheme))} role={roleOrder.indexOf(id)}/><figcaption><strong>{r.name} <span className={r.side==='loyal'?'good-text':'bad-text'}>· {r.title}</span></strong><p>{r.text}</p></figcaption></figure>)}</React.Fragment>)}</div></details><details><summary>Team sizes for 5–10 players</summary><div className="table-scroll"><table><thead><tr><th>Players</th><th>Loyal / Hidden</th><th>Expeditions 1–5</th></tr></thead><tbody>{Object.entries(SIZES).map(([n,a])=><tr key={n}><td>{n}</td><td>{n-EVIL[n]} / {EVIL[n]}</td><td>{a.join(' · ')}</td></tr>)}</tbody></table></div></details><button className="primary" onClick={()=>setHelp(false)}>Back to game <ArrowRight size={17}/></button></section></div>}
 function Home(){
 const {currentTheme,setTheme,setScreen,setHelp,previewBack,setPreviewBack}=useContext(UIContext),active=themes.indexOf(currentTheme);
 return <div className="home-screen chamber-home"><section className="menu-stage"><div className="home-heading"><div className="council-crest" aria-hidden="true"><GameIcon kind="eye" size={48}/></div><h1 tabIndex={-1}>Trust is a weapon.<br/><span>Keep yours hidden.</span></h1><p>A hidden-role game for 5–10 friends. Build your team, uncover the traitors, and protect Merlin.</p><div className="hero-actions"><button className="primary menu-action" onClick={()=>setScreen('create')}><GameIcon kind="crown" size={28}/><span><strong>Host a game</strong><small>Create a private room</small></span><GameIcon kind="arrow" size={22}/></button><button className="secondary menu-action" onClick={()=>setScreen('join')}><GameIcon kind="cards" size={28}/><span><strong>Join a game</strong><small>Enter an invite code</small></span><GameIcon kind="arrow" size={22}/></button></div><button className="text-button menu-learn" onClick={()=>setHelp(true)}><GameIcon kind="scroll" size={21}/>Learn how to play<GameIcon kind="chevron" size={16}/></button></div><section className="deck-showcase" aria-label={`${currentTheme.name} illustrated deck`}><div className="deck-stage" aria-hidden="true">{[1,0,8].map((role,i)=><div key={`${currentTheme.id}-${role}`} className={`showcase-card showcase-card-${i} foil-surface`}><ThemeArt index={active} role={role}/><span className="showcase-card-label">{role===8?<GameIcon kind="eye" size={30}/>:ROLES[roleOrder[role]].name}</span></div>)}</div><div className="deck-world-title"><span lang="hi">{currentTheme.symbol}</span><h2>{currentTheme.name}</h2><span>{currentTheme.subtitle}</span></div><div className="world-gallery" aria-label="Choose your illustrated world">{themes.map((t,i)=><button key={t.id} className={`world-panel world-${t.id} ${t===currentTheme?'selected':''}`} aria-label={`Choose ${t.name}: ${t.subtitle}`} aria-pressed={t===currentTheme} onClick={()=>setTheme(t.id)}><ThemeArt index={i} role={8}/><span><strong>{t.name}</strong></span><span className="world-pick">{t===currentTheme?<Check size={15}/>:<Plus size={15}/>}</span></button>)}</div><div className="world-detail"><p>Choose your deck. The artwork changes; the rules stay the same.</p><button className="text-button" aria-expanded={previewBack} onClick={()=>setPreviewBack(!previewBack)}><GameIcon kind="cards" size={20}/>{previewBack?'Close deck preview':'Explore this deck'}<MorphIcon icon={previewBack?ChevronDownData:ChevronRightData} size={16} spring="snappy" reducedMotion="user"/></button></div></section></section>{previewBack&&<section className="deck-preview" aria-label={`${currentTheme.name} deck preview`}><div><h2>Meet the roles.</h2><p>Eight roles. One shared card back.<br/>{' '}Same rules, a different world.</p></div><div className="deck-strip">{[0,1,5,8].map(r=><figure key={r} className="foil-surface deck-sample"><ThemeArt index={active} role={r}/><figcaption>{r===8?'Common back':ROLES[roleOrder[r]].name}</figcaption></figure>)}</div></section>}</div>
 }
 function Scoreboard(){const {state}=useContext(UIContext);if(state.phase==='reveal')return null;const good=state.results.filter(r=>r.success).length,bad=state.results.length-good;return <div className="council-score" aria-label="Expedition score"><div className="score-side good-text"><GameIcon kind="seal" size={24}/><span>Loyal court</span><span className="score-gems" role="img" aria-label={`${good} of 3 successful expeditions`}>{[0,1,2].map(i=><i key={i} className={i<good?'earned':''}/>)}</span><strong>{good}<small> / 3</small></strong></div><span className="score-divider"><GameIcon kind="eye" size={25}/></span><div className="score-side bad-text"><GameIcon kind="sword" size={24}/><span>Hidden circle</span><span className="score-gems" role="img" aria-label={`${bad} of 3 failed expeditions`}>{[0,1,2].map(i=><i key={i} className={i<bad?'earned':''}/>)}</span><strong>{bad}<small> / 3</small></strong></div></div>}

function PowerCards(){
 const {state,isHost,pending,command}=useContext(UIContext),n=Math.max(5,state.players.length),evilCount=1+state.options.filter(k=>ROLES[k].side==='shadow').length,over=evilCount>EVIL[n];
 return <section className="power-cards" aria-labelledby="power-title"><h2 id="power-title">Special roles</h2><p className="small muted">{isHost?'Choose the roles for this game.':'Your host chooses the roles for this game.'} Everyone can see the selection; assignments stay secret.</p><div className="fixed-powers">{['seer','blade'].map(k=><div key={k}><LockKeyhole size={14}/><strong>{ROLES[k].name}</strong><span>Always included</span></div>)}</div><div className="optional-powers">{['keeper','impostor','veiled','outcast'].map(k=><label className={`option-check ${state.options.includes(k)?'included':''}`} key={k}><input type="checkbox" aria-label={`Include ${ROLES[k].name}`} checked={state.options.includes(k)} disabled={!isHost||pending} onChange={()=>command('settings',{theme:state.theme,options:state.options.includes(k)?state.options.filter(x=>x!==k):[...state.options,k]})}/><span><strong>{ROLES[k].name} · {ROLES[k].title}</strong><small>{ROLES[k].text}</small></span></label>)}</div><p className={over?'power-warning':'small muted'} role={over?'status':undefined}>{over?`This selection needs more evil seats. For ${n} players, keep at most ${EVIL[n]-1} optional evil ${EVIL[n]-1===1?'role':'roles'} alongside the Assassin, or invite more friends.`:`${state.options.length} optional ${state.options.length===1?'role':'roles'} selected. Remaining seats become Loyal Servants of Arthur or Minions of Mordred.`}</p><p className="small muted power-capacity">{state.players.length<5?'With 5 players':'With '+n+' players'}: {n-EVIL[n]} good · {EVIL[n]} evil. Special roles use these seats.</p></section>
}
function CouncilSeats(){
 const {state,me}=useContext(UIContext),count=Math.max(5,state.players.length);
 return <><div className="council-board round-table" aria-label="Council seating"><div className="council-center"><ScanEye size={36} strokeWidth={1} aria-hidden="true"/><span>THE COUNCIL</span><strong>{state.players.filter(p=>p.ready).length}<small> / {state.players.length} ready</small></strong></div><div className="council-seats">{Array.from({length:count},(_,i)=>{
  const p=state.players[i],angle=(i/count)*Math.PI*2-Math.PI/2;
  const position={left:`${50+37*Math.cos(angle)}%`,top:`${50+37*Math.sin(angle)}%`};
  const status=p?(!p.online?'Reconnecting':p.ready?'Ready':'Not ready'):'Open seat';
  return <div key={p?.id||`empty${i}`} style={position} className={`council-seat ${p?'':'empty'} ${p?.ready?'ready':''} ${p&&!p.online?'offline':''}`} title={p?`${p.name}${p.id===me.id?' (you)':''} · ${status}`:'Open seat'} aria-label={p?`${p.name}${p.id===me.id?', you':''}${p.id===state.host?', host':''}, ${status}`:`Seat ${i+1}, open`}><span className="seat-avatar" aria-hidden="true">{p?p.name.charAt(0).toUpperCase():<Plus size={20}/>} {p?.id===state.host&&<Crown size={14}/>} {p?.ready&&<span className="seat-ready"><Check size={12}/></span>}</span><strong aria-hidden="true">{p?p.name:'Open seat'}</strong></div>
 })}</div></div><details className="seating-details"><summary>Player details · {state.players.length} at the table</summary><PlayerList/></details></>
}
function PhaseGuide(){
 const {state,isLeader}=useContext(UIContext);if(['reveal','finished'].includes(state.phase))return null;
 const stages=[['proposal','Choose'],['vote','Vote'],['quest','Expedition'],['accusation','Final call']];const phase=state.phase.replace('Result','');let active=stages.findIndex(([id])=>id===phase);
 return <div className="phase-guide"><div className="phase-stages" aria-label="Round stages">{stages.map(([id,name],i)=><span key={id} className={i===active?'active':''} aria-current={i===active?'step':undefined}><span>{i<active?<Check size={12}/>:i+1}</span>{name}{i<3&&<ChevronRight size={13}/>}</span>)}</div><span className="turn-label">{state.phase==='proposal'?(isLeader?'Your turn to lead':'Talk it through together'):state.phase==='vote'?(state.me.voted?'Vote sealed':'Your vote matters'):state.phase==='quest'?'Cards stay anonymous':state.phase==='accusation'?'Protect the final secret':'The council has spoken'}</span></div>
}

createRoot(document.getElementById('root')).render(<App/>);

function LobbyStatus(){
 const {state,isHost}=useContext(UIContext);
 const missing=Math.max(0,5-state.players.length),offline=state.players.filter(p=>!p.online),waiting=state.players.filter(p=>!p.ready);
 const over=1+state.options.filter(k=>ROLES[k].side==='shadow').length>EVIL[Math.max(5,state.players.length)];
 const message=missing?`Invite ${missing} more ${missing===1?'friend':'friends'} to reach the minimum of 5.`:over?'Too many hidden-circle roles. Adjust Special roles before dealing.':offline.length?`Waiting for ${offline.map(p=>p.name).join(', ')} to reconnect.`:waiting.length?`Waiting for ${waiting.map(p=>p.name).join(', ')} to ready up.`:isHost?'Everyone is ready. Deal the roles to begin.':'Everyone is ready. Your host will deal the roles.';
 return <p className="lobby-status" role="status"><Users size={18}/><span>{message}</span></p>;
}

function QuestDecision(){
 const {state,pending,command}=useContext(UIContext),[choice,setChoice]=useState(null);
 useEffect(()=>{const hide=()=>{if(document.hidden)setChoice(null)};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[]);
 return <div className="quest-decision"><div className="quest-actions" role="group" aria-label="Choose a private expedition card"><button className="quest-choice support" aria-pressed={choice===true} disabled={pending} onClick={()=>setChoice(true)}><GameIcon kind="seal" size={44}/><strong>Support</strong><span>Help the expedition succeed</span><span className="choice-state">{choice===true?<><Check size={16}/>Selected</>:'Select card'}</span></button>{ROLES[state.me.role].side==='shadow'&&<button className="quest-choice sabotage" aria-pressed={choice===false} disabled={pending} onClick={()=>setChoice(false)}><GameIcon kind="sword" size={44}/><strong>Sabotage</strong><span>Work against the expedition</span><span className="choice-state">{choice===false?<><Check size={16}/>Selected</>:'Select card'}</span></button>}</div><p className="decision-hint">{choice===null?'Choose a card, then seal it.':`${choice?'Support':'Sabotage'} selected. You can change your choice before sealing.`}</p><button className="primary wide" disabled={choice===null||pending} onClick={()=>command('quest',{support:choice})}><LockKeyhole size={18}/>{pending?'Sealing card…':'Seal my card'}</button><p className="form-note">Once sealed, your card cannot be changed.</p></div>;
}
